name: Build Docker image and publish

permissions: {}

on:
  push:
    branches: [ main ]
jobs:
  extract_docker_metadata:
    name: Extract metadata (tags, labels) for Docker
    runs-on: ubuntu-latest
    outputs: 
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: get metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mozilla/blurts-server
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value={{sha}},event=tag

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: [extract_docker_metadata]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create version.json
        run: |
          echo "{\"commit\":\"$GITHUB_SHA\",\"version\":\"$GITHUB_REF\",\"source\":\"https://github.com/$GITHUB_REPOSITORY\",\"build\":\"$GITHUB_RUN_ID\"}" > version.json

      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      - name: Build Docker image
        env:
          UPLOAD_SENTRY_SOURCEMAPS: true
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ github.ref_name }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          docker build --tag blurts-server \
            --build-arg SENTRY_RELEASE="$SENTRY_RELEASE" \
            --build-arg NEXT_PUBLIC_SENTRY_DSN="$NEXT_PUBLIC_SENTRY_DSN" \
            --secret id=SENTRY_AUTH_TOKEN \
            .

      - name: Deploy to Dockerhub
        env:
          DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}
        run: |
          # deploy main
          docker tag blurts-server ${{ needs.extract_docker_metadata.outputs.tags }}
          docker push ${{ needs.extract_docker_metadata.outputs.tags }}
  push_to_gcp_gar:
    name: "Build and push to GCP GAR (V2 Environment)"
    needs: [extract_docker_metadata]
    uses: ./.github/workflows/reuse-build-and-push.yml
    secrets: inherit
    with:
      image-name: blurts-server
      image-tag: ${{ needs.extract_docker_metadata.outputs.tags}}
      gar-region: us
      workload-identity-provider: ${{ vars.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
      push: true
